{{- if .Values.ExternalSecret.enabled }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}
spec:
  refreshInterval: "60s"
  secretStoreRef:
    name: vault-app
    kind: ClusterSecretStore
  target:
    name: {{ .Release.Name }}
  dataFrom:
  - extract:
      key: {{ .Values.ExternalSecret.key | default .Release.Name }}
{{- end }}
{{- range $.Values.ExternalSecret.extra }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata: {{ .metadata | toYaml | nindent 2 }}
spec: {{ .spec | toYaml | nindent 2 }}
{{- end }}
